name: healthnest
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_country_picker: ^0.1.6
  font_awesome_flutter: ^8.5.0
  share: ^0.6.3+5
  flutter_reaction_button: ^0.1.3
  carousel_slider: ^1.4.1
  audioplayers: ^0.13.5
  path_provider: ^1.5.1

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2


dev_dependencies:
  # flutter_test:
  #  sdk: flutter

flutter:

  uses-material-design: true

  assets:
      - assets/img/

  fonts:
    - family: nunito
      fonts:
        - asset: assets/font/nunito/nunito-regular.ttf